### ISSUE TITLE
Error: Method name not allowed: HEAD /service-status

### ISSUE THREAD

**Issue by KyleAMathews** [atomantic/hapi-and-healthy#8]
Getting this error in Hapi 8.3.1

```
Error: Method name not allowed: HEAD /service-status
  at Object.exports.assert (/root/RelateRocket/page-server/node_modules/hapi/node_modules/hoek/lib/index.js:678:11)
  at new module.exports.internals.Route (/root/RelateRocket/page-server/node_modules/hapi/lib/route.js:44:10)
  at [object Object].internals.Connection._addRoute (/root/RelateRocket/page-server/node_modules/hapi/lib/connection.js:352:17)
  at [object Object].internals.Connection._route (/root/RelateRocket/page-server/node_modules/hapi/lib/connection.js:344:18)
  at [object Object].internals.Plugin._apply (/root/RelateRocket/page-server/node_modules/hapi/lib/plugin.js:440:14)
  at [object Object].internals.Plugin.route (/root/RelateRocket/page-server/node_modules/hapi/lib/plugin.js:415:10)
  at Object.exports.register (/root/RelateRocket/page-server/node_modules/hapi-and-healthy/index.js:217:16)
  at /root/RelateRocket/page-server/node_modules/hapi/lib/plugin.js:242:14
  at iterate (/root/RelateRocket/page-server/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at Object.exports.serial (/root/RelateRocket/page-server/node_modules/hapi/node_modules/items/lib/index.js:38:9)
  at [object Object].internals.Plugin.register (/root/RelateRocket/page-server/node_modules/hapi/lib/plugin.js:224:11)
  at Object.<anonymous> (/root/RelateRocket/page-server/index.coffee:35:8)
  at Object.<anonymous> (/root/RelateRocket/page-server/index.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.exports.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:131:23)
  at compileScript (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:208:29)
  at compilePath (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:161:14)
  at Object.exports.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:96:20)
  at Object.<anonymous> (/usr/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by atomantic** [comment]
Do you by any chance have a default cors configuration for routes that removes HEAD as a viable method?

**Comment by KyleAMathews** [comment]
Thanks
